version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: subscription-db
    environment:
      POSTGRES_DB: subscription_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: subscription-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=subscription_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=8080
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: 